id: I94E34ACA
legacy_id: P000724
ocr_import_info:
  bdrc_scan_id: W3CN7829
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T02:20:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:49:52.292742+00:00'
last_modified: 2022-09-03 23:51:58.741426
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7829
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7829
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9628528194654717
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN7834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7834
      total_pages: 438
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN7834.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9675072596170433
    legacy_id: v004
  I3CN7832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7832
      total_pages: 238
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN7832.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9719056259836755
    legacy_id: v002
  I3CN7836:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7836
      total_pages: 404
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN7836.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9636582779476562
    legacy_id: v006
  I3CN7841:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7841
      total_pages: 372
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3CN7841.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.964275443521988
    legacy_id: v011
  I3CN7837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7837
      total_pages: 368
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN7837.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9654364563238262
    legacy_id: v007
  I3CN7840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7840
      total_pages: 390
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3CN7840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9673102861090163
    legacy_id: v010
  I3CN7831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7831
      total_pages: 566
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7831.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9420771049305144
    legacy_id: v001
  I3CN7835:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7835
      total_pages: 416
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN7835.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9693598809386419
    legacy_id: v005
  I3CN7839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7839
      total_pages: 382
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3CN7839.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9700819504989381
    legacy_id: v009
  I3CN7833:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7833
      total_pages: 358
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN7833.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9714459848210022
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
